version: '3.1'

services:
  db:
    container_name: mysqldb-8.3.0
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
    ports:
      - 3306:3306

  adminer:
    container_name: adminer-4.8.1-standalone
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 9080:8080